### ISSUE TITLE
confirm add-steps and and failure-accrual work with docker for mac

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd-examples#106]
we observed the `add-steps` demo failing with docker for mac, specifically the slow_cooker instances were unable to connect to the application instances.

**Comment by klingerf** [comment]
We should also verify that the [linkerd-tcp](https://github.com/BuoyantIO/linkerd-examples/tree/master/linkerd-tcp) example works with docker for mac.

**Comment by esbie** [comment]
Confirmed adds-steps and failure-accrual work for me, Docker for Mac Version 17.03.1-ce-rc1-mac3 

In linkerd-tcp, linkerd-tcp fails to connect to namerd. continuing investigation...

**Comment by esbie** [comment]
related: https://github.com/docker/compose/issues/3800

**Comment by esbie** [comment]
namerd connection caused in part by https://github.com/linkerd/linkerd-tcp/issues/9

**Comment by rmars** [comment]
same. add-steps and failure-accrual work for me. linkerd-tcp does not.
Docker for Mac version 17.03.1-ce-rc1-mac3
