### ISSUE TITLE
GCE LoadBalancer is pending indefinitely

### ISSUE THREAD

**Issue by verdverm** [linkerd/linkerd-examples#148]
I've followed along several of the blog posts in the "A Service Mesh for Kubernetes" series. Each time, the LoadBalancer is not created and the IP is pending indefinitely.

Maybe I am missing a service account / the correct permissions on the VMs?

**Comment by siggy** [comment]
Hi @verdverm. Thanks for trying out the blog posts. Are you running on Google Container Engine (GKE)? If not have a look at:
https://discourse.linkerd.io/t/flavors-of-kubernetes/53

I'm going to close this issue for now, as we typically troubleshoot these kinds of issues in https://discourse.linkerd.io. Feel free to start a conversation in there, include as much info about your config as possible. Thank!

**Comment by verdverm** [comment]
https://discourse.linkerd.io/t/gce-loadbalancer-ip-is-pending-indefinitely
