### ISSUE TITLE
Add support to modify HTTP status code using identifier in linkerd plugins

### ISSUE THREAD

**Issue by SurajMenon** [linkerd/linkerd-examples#150]
I am using linkerD to set up an authorization plugin, in Java. Currently I am using an Identifier to intercept the request & check if the user is authorized. (Using : https://github.com/linkerd/linkerd-examples/tree/master/plugins/header-classifier as an example)

If the user is not authorized, the request should not reach the backend service.  I am throwing a runtime exception in such cases (do let me know if there is another way for preventing the request to reach the backend). Linkerd sends the response as 502 Bad Gateway. Linkerd should have a mechanism by which I can specify the HTTP status code I want to send back.

I tried using a responseClassifier along with the identifier, but it looks like the responseClassifier does not get invoked when the exception is thrown.

**Comment by wmorgan** [comment]
@SurajMenon did you figure it out? What was the issue?

**Comment by esbie** [comment]
moved to https://github.com/linkerd/linkerd/issues/1465
