### ISSUE TITLE
Kubernetes 1.6.4 throws `PRI *` request exceptions on `k8s/linkerd.yml`

### ISSUE THREAD

**Issue by Dominik-K** [linkerd/linkerd-examples#163]
Applying the current [`k8s/linkerd.yml`]( https://github.com/linkerd/linkerd-examples/blob/master/k8s-daemonset/k8s/linkerd.yml) example on Kubernetes 1.6.4 (master & nodes) results in the following exceptions:

    W 0718 14:40:28.865 UTC THREAD31: Exception propagated to the default monitor (upstream address: /10.52.6.74:47528, downstream address: n/a, label: 0.0.0.0/4140).
    io.buoyant.router.RoutingFactory$UnknownDst: Unknown destination: Request("PRI *", from /10.52.6.74:47528) / Host header is absent

    W 0718 14:40:28.881 UTC THREAD32: Exception propagated to the default monitor (upstream address: /10.52.6.74:47530, downstream address: n/a, label: 0.0.0.0/4140).
    io.buoyant.router.RoutingFactory$UnknownDst: Unknown destination: Request("PRI *", from /10.52.6.74:47530) / Host header is absent

    [indefinitely(?) stepping through all even port numbers, same IP]

They don't occur on Kubernetes 1.5.2 (master: 1.5.7). Tested both on Google Container Engine.

The request `PRI *` seems to be a [HTTP/2 request](https://tools.ietf.org/html/rfc7540#section-11.6).

**Comment by olix0r** [comment]
`PRI *` is part of the HTTP/2 handshake, and this error makes it seem that you're using an _http_ router (and not _h2_).  You'll want to configure an _h2_ router in linkerd to send http2 traffic through linkerd.

**Comment by Dominik-K** [comment]
@olix0r I didn't made any requests to the `service` yet. Deployed it in a newly created Kubernetes namespace (both K8s versions). 
Maybe another service in the clusters tries all ports but that's unlikely.

**Comment by olix0r** [comment]
I'd try to figure what's on that IP.  Something in your network is trying to establish HTTP/2 connections to linkerd on its http port. linkerd should be working properly otherwise, though.

**Comment by Dominik-K** [comment]
I tested it again on a barely new cluster. Now the exceptions are gone even on Kubernetes 1.6.4. 
Sorry for the too fast issue creation.
