### ISSUE TITLE
ThirdPartyResources to be removed in Kubernetes 1.8

### ISSUE THREAD

**Issue by krak3n** [linkerd/linkerd-examples#183]
As https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-third-party-resource/ describes `ThirdPartyResource` will be removed in 1.8.

> ThirdPartyResource is deprecated as of Kubernetes 1.7 and has been removed in version 1.8 in accordance with the deprecation policy for beta features.
> 
> To avoid losing data stored in ThirdPartyResources, you must migrate to CustomResourceDefinition before upgrading to Kubernetes 1.8 or higher.

I guess the examples need to be updated to use `CustomResourceDefinition` - I'm having a go at getting stuff working using `CustomResourceDefinition` so we'll see

**Comment by esbie** [comment]
Yep we have seen that notice as part of 1.8, thank you for filing this issue! Namerd will need to be updated to support CustomResourceDefinitions before the examples are updated.

**Comment by krak3n** [comment]
Ah ok thank you @esbie I did have a go at using `CustomResourceDefinitions` but it didn't work so that would be why :smile:

**Comment by siggy** [comment]
replace `ThirdPartyResource` from:
https://github.com/linkerd/linkerd-examples/blob/master/k8s-daemonset/k8s/namerd.yml#L1

with `CustomResourceDefinition`:
https://github.com/linkerd/linkerd/blob/master/namerd/examples/k8s/3rdparty.yaml

**Comment by krak3n** [comment]
Thanks guys :+1:

**Comment by siggy** [comment]
I'm going to leave this open until we've updated the namerd.yml example, or provided a separate k8s 1.8 example.

**Comment by dadjeibaah** [comment]
New namerd yaml has been added https://github.com/linkerd/linkerd-examples/blob/master/k8s-daemonset/k8s/namerd.yml
