### ISSUE TITLE
Update vendored grpc-go for helloworld (and any other go-grpc examples) to be >= grpc-go 1.3.0

### ISSUE THREAD

**Issue by briansmith** [linkerd/linkerd-examples#193]
Version 1.2 of grpc-go has a bug where the `:authority` header doesn't have the port set when the port isn't the default port. This creates interop problems.

- [ ] Update the version of grpc-go to use a version where the bug is fixed, at lesat grpc 1.3.0.
- [ ] Publish new docker images tagged with a new version number and update the Kubernetes (and other) configuration files to reference the new image.
- [ ] Update blog posts, etc. accordingly.

**Comment by siggy** [comment]
no references to `helloworld` version in the blog posts, and api did not change.
