### ISSUE TITLE
Permission problems running "hello world" example on 1.8.7-gke.1 

### ISSUE THREAD

**Issue by luismoramedina** [linkerd/linkerd-examples#212]
Hi,

I was not able to run the helloworld sample in google cloud 1.8.7-gke.1. I follow the instructions but i got this error message in l5d log:

----
E 0315 08:23:35.103 UTC THREAD29: retrying k8s request to /api/v1/namespaces/default/endpoints/world-v1 on unexpected response code 403 with message {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"endpoints \"world-v1\" is forbidden: User \"system:serviceaccount:default:default\" cannot get endpoints in the namespace \"default\": Unknown user \"system:serviceaccount:default:default\"","reason":"Forbidden","details":{"name":"world-v1","kind":"endpoints"},"code":403}
----

The workarround was give "default" service account permissions to requests endpoints api in the default namespace and everything works now.

Regards.

**Comment by hawkw** [comment]
Hi @luismoramedina, were you trying to deploy the basic Linkerd configuration (i.e. `linkerd-examples/k8s-daemonset/k8s/linkerd.yml`) in a cluster with RBAC enabled? You might be interested to note that we also have an [example configuration for RBAC clusters](https://github.com/linkerd/linkerd-examples/tree/master/k8s-daemonset#rbac) which will perform more granular configuration of service accounts and permissions.

**Comment by luismoramedina** [comment]
Oops! I missed that. I'm working on google cloud so i think rbac is enabled. Thanks a lot @hawkw!

**Comment by hawkw** [comment]
Glad I could help!
