### ISSUE TITLE
Grafana seems to fail in the docker-compose command

### ISSUE THREAD

**Issue by wahlfeld** [linkerd/linkerd-examples#246]
Grafana seems to fail in the docker-compose command, possibly due to old version? New version seems to require elevated privileges to run apt-get. See PR here: https://github.com/linkerd/linkerd-examples/pull/245

> Step 2/6 : RUN apt-get update &&     apt-get -y --no-install-recommends install curl
>  ---> Running in 6031a5d60d5e
> Ign http://httpredir.debian.org jessie InRelease
> Ign http://httpredir.debian.org jessie-updates InRelease
> Get:1 http://httpredir.debian.org jessie Release.gpg [2420 B]
> Get:2 http://security.debian.org jessie/updates InRelease [44.9 kB]
> Ign http://httpredir.debian.org jessie-updates Release.gpg
> Get:3 http://httpredir.debian.org jessie Release [148 kB]
> Ign http://httpredir.debian.org jessie-updates Release
> Err http://httpredir.debian.org jessie-updates/main amd64 Packages
> 
> Err http://httpredir.debian.org jessie-updates/main amd64 Packages
> 
> Err http://httpredir.debian.org jessie-updates/main amd64 Packages
> 
> Err http://httpredir.debian.org jessie-updates/main amd64 Packages
> 
> Err http://httpredir.debian.org jessie-updates/main amd64 Packages
>   404  Not Found
> Get:4 http://httpredir.debian.org jessie/main amd64 Packages [9098 kB]
> Get:5 http://security.debian.org jessie/updates/main amd64 Packages [822 kB]
> Fetched 10.1 MB in 5s (1766 kB/s)
> W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.
> ERROR: Service 'grafana' failed to build: The command '/bin/sh -c apt-get update &&     apt-get -y --no-install-recommends install curl' returned a non-zero code: 100

**Comment by siggy** [comment]
Fixed via #245.
