### ISSUE TITLE
ECS example, host port 53 - address already in use

### ISSUE THREAD

**Issue by gitisz** [linkerd/linkerd-examples#252]
I am experimenting with the ECS linkerd example, however in our AMI we have dnsmasq owning port 53 on the host. As a result when launching the taskDefinition, the consul-agent fails: 

```
 Error starting userland proxy: listen udp 0.0.0.0:53: bind: address already in use
```

What might you recommend to start the consul-agent?  Would forwarding DNS to 127.0.0.1 to the container on port 8600 be the right option?  Or should I just disable dnsmasq and allow the container to bind to host port 53?

**Comment by siggy** [comment]
@gitisz I think either approach sounds reasonable, in case you haven't seen this already, your forwarding approach is documented here: https://learn.hashicorp.com/consul/security-networking/forwarding#dnsmasq-setup

I'm going to close this issue for now, hop into [Linkerd Slack](https://slack.linkerd.io) if you have more questions.
