### ISSUE TITLE
[DOC]: clarify if this repository is for linkerd v1 or v2

### ISSUE THREAD

**Issue by alonsocamaro** [linkerd/linkerd-examples#254]
and any differences that may apply in each case

**Comment by wmorgan** [comment]
Great idea @alonsocamaro! @siggy and @grampelberg, what do you think?

**Comment by siggy** [comment]
Agreed! It should be straightforward to document this. Probably 95% of this repo is for Linkerd v1 (since Linkerd v2 _just works_ we haven't needed to create any example configs). So for the moment, just assume everything in this repo is Linkerd v1 unless it explicitly says v2.
